development:
  adapter: postgresql
  encoding: unicode
  database: gatekeeper
  pool: 2
  username: sonatatest
  password: sonata
  host: 172.18.0.2

production:
  adapter: postgresql
  encoding: unicode
  database: gatekeeper
  pool: 2
  username: sonatatest
  password: sonata
  host: 172.18.0.2